#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidGPSExample.Resource", IsApplication=true)]

namespace AndroidGPSExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.Boolean.abc_action_bar_embed_tabs = global::AndroidGPSExample.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Forms.Platform.Resource.Color.primary_text_default_material_dark = global::AndroidGPSExample.Resource.Color.primary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Resource.Color.ripple_material_light = global::AndroidGPSExample.Resource.Color.ripple_material_light;
			global::Xamarin.Forms.Platform.Resource.Color.secondary_text_default_material_dark = global::AndroidGPSExample.Resource.Color.secondary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Resource.Color.secondary_text_default_material_light = global::AndroidGPSExample.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_large_icon_height = global::AndroidGPSExample.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_large_icon_width = global::AndroidGPSExample.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Forms.Platform.Resource.Dimension.notification_subtext_size = global::AndroidGPSExample.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Forms.Platform.Resource.Drawable.notification_template_icon_bg = global::AndroidGPSExample.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Forms.Platform.Resource.Id.action0 = global::AndroidGPSExample.Resource.Id.action0;
			global::Xamarin.Forms.Platform.Resource.Id.action_divider = global::AndroidGPSExample.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Resource.Id.cancel_action = global::AndroidGPSExample.Resource.Id.cancel_action;
			global::Xamarin.Forms.Platform.Resource.Id.chronometer = global::AndroidGPSExample.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Resource.Id.end_padder = global::AndroidGPSExample.Resource.Id.end_padder;
			global::Xamarin.Forms.Platform.Resource.Id.icon = global::AndroidGPSExample.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Resource.Id.info = global::AndroidGPSExample.Resource.Id.info;
			global::Xamarin.Forms.Platform.Resource.Id.line1 = global::AndroidGPSExample.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Resource.Id.line3 = global::AndroidGPSExample.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Resource.Id.media_actions = global::AndroidGPSExample.Resource.Id.media_actions;
			global::Xamarin.Forms.Platform.Resource.Id.none = global::AndroidGPSExample.Resource.Id.none;
			global::Xamarin.Forms.Platform.Resource.Id.normal = global::AndroidGPSExample.Resource.Id.normal;
			global::Xamarin.Forms.Platform.Resource.Id.status_bar_latest_event_content = global::AndroidGPSExample.Resource.Id.status_bar_latest_event_content;
			global::Xamarin.Forms.Platform.Resource.Id.text = global::AndroidGPSExample.Resource.Id.text;
			global::Xamarin.Forms.Platform.Resource.Id.text2 = global::AndroidGPSExample.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Resource.Id.time = global::AndroidGPSExample.Resource.Id.time;
			global::Xamarin.Forms.Platform.Resource.Id.title = global::AndroidGPSExample.Resource.Id.title;
			global::Xamarin.Forms.Platform.Resource.Integer.cancel_button_image_alpha = global::AndroidGPSExample.Resource.Integer.cancel_button_image_alpha;
			global::Xamarin.Forms.Platform.Resource.Integer.status_bar_notification_info_maxnum = global::AndroidGPSExample.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_media_action = global::AndroidGPSExample.Resource.Layout.notification_media_action;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_media_cancel_action = global::AndroidGPSExample.Resource.Layout.notification_media_cancel_action;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media = global::AndroidGPSExample.Resource.Layout.notification_template_big_media;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media_narrow = global::AndroidGPSExample.Resource.Layout.notification_template_big_media_narrow;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_media = global::AndroidGPSExample.Resource.Layout.notification_template_media;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_part_chronometer = global::AndroidGPSExample.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_part_time = global::AndroidGPSExample.Resource.Layout.notification_template_part_time;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::AndroidGPSExample.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::AndroidGPSExample.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.status_bar_notification_info_overflow = global::AndroidGPSExample.Resource.String.status_bar_notification_info_overflow;
			global::XLabs.Forms.Resource.Boolean.abc_action_bar_embed_tabs = global::AndroidGPSExample.Resource.Boolean.abc_action_bar_embed_tabs;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::AndroidGPSExample.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::AndroidGPSExample.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::AndroidGPSExample.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::AndroidGPSExample.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::AndroidGPSExample.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::AndroidGPSExample.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::AndroidGPSExample.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::AndroidGPSExample.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::AndroidGPSExample.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::AndroidGPSExample.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::AndroidGPSExample.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::AndroidGPSExample.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Color.primary_text_default_material_dark = global::AndroidGPSExample.Resource.Color.primary_text_default_material_dark;
			global::XLabs.Forms.Resource.Color.ripple_material_light = global::AndroidGPSExample.Resource.Color.ripple_material_light;
			global::XLabs.Forms.Resource.Color.secondary_text_default_material_dark = global::AndroidGPSExample.Resource.Color.secondary_text_default_material_dark;
			global::XLabs.Forms.Resource.Color.secondary_text_default_material_light = global::AndroidGPSExample.Resource.Color.secondary_text_default_material_light;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::AndroidGPSExample.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::AndroidGPSExample.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::AndroidGPSExample.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::AndroidGPSExample.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::AndroidGPSExample.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Dimension.notification_large_icon_height = global::AndroidGPSExample.Resource.Dimension.notification_large_icon_height;
			global::XLabs.Forms.Resource.Dimension.notification_large_icon_width = global::AndroidGPSExample.Resource.Dimension.notification_large_icon_width;
			global::XLabs.Forms.Resource.Dimension.notification_subtext_size = global::AndroidGPSExample.Resource.Dimension.notification_subtext_size;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::AndroidGPSExample.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::AndroidGPSExample.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Drawable.notification_template_icon_bg = global::AndroidGPSExample.Resource.Drawable.notification_template_icon_bg;
			global::XLabs.Forms.Resource.Id.action0 = global::AndroidGPSExample.Resource.Id.action0;
			global::XLabs.Forms.Resource.Id.action_divider = global::AndroidGPSExample.Resource.Id.action_divider;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::AndroidGPSExample.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::AndroidGPSExample.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.cancel_action = global::AndroidGPSExample.Resource.Id.cancel_action;
			global::XLabs.Forms.Resource.Id.chronometer = global::AndroidGPSExample.Resource.Id.chronometer;
			global::XLabs.Forms.Resource.Id.end_padder = global::AndroidGPSExample.Resource.Id.end_padder;
			global::XLabs.Forms.Resource.Id.icon = global::AndroidGPSExample.Resource.Id.icon;
			global::XLabs.Forms.Resource.Id.info = global::AndroidGPSExample.Resource.Id.info;
			global::XLabs.Forms.Resource.Id.left_arrow = global::AndroidGPSExample.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.line1 = global::AndroidGPSExample.Resource.Id.line1;
			global::XLabs.Forms.Resource.Id.line3 = global::AndroidGPSExample.Resource.Id.line3;
			global::XLabs.Forms.Resource.Id.media_actions = global::AndroidGPSExample.Resource.Id.media_actions;
			global::XLabs.Forms.Resource.Id.none = global::AndroidGPSExample.Resource.Id.none;
			global::XLabs.Forms.Resource.Id.normal = global::AndroidGPSExample.Resource.Id.normal;
			global::XLabs.Forms.Resource.Id.right_arrow = global::AndroidGPSExample.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.status_bar_latest_event_content = global::AndroidGPSExample.Resource.Id.status_bar_latest_event_content;
			global::XLabs.Forms.Resource.Id.text = global::AndroidGPSExample.Resource.Id.text;
			global::XLabs.Forms.Resource.Id.text2 = global::AndroidGPSExample.Resource.Id.text2;
			global::XLabs.Forms.Resource.Id.time = global::AndroidGPSExample.Resource.Id.time;
			global::XLabs.Forms.Resource.Id.title = global::AndroidGPSExample.Resource.Id.title;
			global::XLabs.Forms.Resource.Integer.cancel_button_image_alpha = global::AndroidGPSExample.Resource.Integer.cancel_button_image_alpha;
			global::XLabs.Forms.Resource.Integer.status_bar_notification_info_maxnum = global::AndroidGPSExample.Resource.Integer.status_bar_notification_info_maxnum;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::AndroidGPSExample.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::AndroidGPSExample.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::AndroidGPSExample.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::AndroidGPSExample.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.notification_media_action = global::AndroidGPSExample.Resource.Layout.notification_media_action;
			global::XLabs.Forms.Resource.Layout.notification_media_cancel_action = global::AndroidGPSExample.Resource.Layout.notification_media_cancel_action;
			global::XLabs.Forms.Resource.Layout.notification_template_big_media = global::AndroidGPSExample.Resource.Layout.notification_template_big_media;
			global::XLabs.Forms.Resource.Layout.notification_template_big_media_narrow = global::AndroidGPSExample.Resource.Layout.notification_template_big_media_narrow;
			global::XLabs.Forms.Resource.Layout.notification_template_media = global::AndroidGPSExample.Resource.Layout.notification_template_media;
			global::XLabs.Forms.Resource.Layout.notification_template_part_chronometer = global::AndroidGPSExample.Resource.Layout.notification_template_part_chronometer;
			global::XLabs.Forms.Resource.Layout.notification_template_part_time = global::AndroidGPSExample.Resource.Layout.notification_template_part_time;
			global::XLabs.Forms.Resource.Layout.week = global::AndroidGPSExample.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::AndroidGPSExample.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::AndroidGPSExample.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::AndroidGPSExample.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::AndroidGPSExample.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::AndroidGPSExample.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::AndroidGPSExample.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::AndroidGPSExample.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.String.status_bar_notification_info_overflow = global::AndroidGPSExample.Resource.String.status_bar_notification_info_overflow;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::AndroidGPSExample.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::AndroidGPSExample.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::AndroidGPSExample.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::AndroidGPSExample.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::AndroidGPSExample.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::AndroidGPSExample.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010024
			public const int font = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int fontProviderAuthority = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int fontProviderCerts = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int fontProviderFetchStrategy = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int fontProviderFetchTimeout = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int fontProviderPackage = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int fontProviderQuery = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int fontStyle = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int fontWeight = 2130772005;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f050020
			public const int calendar_text_selector = 2131034144;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			// aapt resource value: 0x7f050021
			public const int common_google_signin_btn_text_dark = 2131034145;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark_default = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_dark_disabled = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int common_google_signin_btn_text_dark_focused = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int common_google_signin_btn_text_dark_pressed = 2131034132;
			
			// aapt resource value: 0x7f050022
			public const int common_google_signin_btn_text_light = 2131034146;
			
			// aapt resource value: 0x7f050015
			public const int common_google_signin_btn_text_light_default = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int common_google_signin_btn_text_light_disabled = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int common_google_signin_btn_text_light_focused = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int common_google_signin_btn_text_light_pressed = 2131034136;
			
			// aapt resource value: 0x7f050023
			public const int common_google_signin_btn_tint = 2131034147;
			
			// aapt resource value: 0x7f05001c
			public const int notification_action_color_filter = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int notification_icon_bg_color = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int notification_material_background_media_default_color = 2131034137;
			
			// aapt resource value: 0x7f05000b
			public const int place_autocomplete_prediction_primary_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int place_autocomplete_prediction_primary_text_highlight = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int place_autocomplete_prediction_secondary_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int place_autocomplete_search_hint = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int place_autocomplete_search_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int place_autocomplete_separator = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int primary_text_default_material_dark = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int ripple_material_light = 2131034142;
			
			// aapt resource value: 0x7f05001b
			public const int secondary_text_default_material_dark = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int secondary_text_default_material_light = 2131034143;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int compat_button_inset_horizontal_material = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int compat_button_inset_vertical_material = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int compat_button_padding_horizontal_material = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int compat_button_padding_vertical_material = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int compat_control_corner_material = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int notification_action_icon_size = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int notification_action_text_size = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int notification_big_circle_margin = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int notification_content_margin_start = 2131099664;
			
			// aapt resource value: 0x7f06001b
			public const int notification_large_icon_height = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int notification_large_icon_width = 2131099676;
			
			// aapt resource value: 0x7f060011
			public const int notification_main_column_padding_top = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int notification_media_narrow_margin = 2131099666;
			
			// aapt resource value: 0x7f06001d
			public const int notification_right_icon_size = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int notification_right_side_padding_top = 2131099663;
			
			// aapt resource value: 0x7f06001e
			public const int notification_small_icon_background_padding = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int notification_small_icon_size_as_large = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int notification_subtext_size = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int notification_top_pad = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int notification_top_pad_large_text = 2131099682;
			
			// aapt resource value: 0x7f060005
			public const int place_autocomplete_button_padding = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int place_autocomplete_powered_by_google_height = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int place_autocomplete_powered_by_google_start = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int place_autocomplete_prediction_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int place_autocomplete_prediction_horizontal_margin = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int place_autocomplete_prediction_primary_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int place_autocomplete_prediction_secondary_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int place_autocomplete_progress_horizontal_margin = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int place_autocomplete_progress_size = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int place_autocomplete_separator_start = 2131099662;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int googleg_disabled_color_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int googleg_standard_color_18 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int notification_action_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_bg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg_low = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_low_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_normal_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_icon_background = 2130837534;
			
			// aapt resource value: 0x7f020025
			public const int notification_template_icon_bg = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int notification_template_icon_low_bg = 2130837542;
			
			// aapt resource value: 0x7f02001f
			public const int notification_tile_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notify_panel_notification_icon_bg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int places_ic_clear = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int places_ic_search = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int powered_by_google_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int powered_by_google_light = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0019
			public const int MapButton = 2131361817;
			
			// aapt resource value: 0x7f0a0022
			public const int action0 = 2131361826;
			
			// aapt resource value: 0x7f0a001f
			public const int action_container = 2131361823;
			
			// aapt resource value: 0x7f0a0026
			public const int action_divider = 2131361830;
			
			// aapt resource value: 0x7f0a0020
			public const int action_image = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int action_text = 2131361825;
			
			// aapt resource value: 0x7f0a0030
			public const int actions = 2131361840;
			
			// aapt resource value: 0x7f0a000a
			public const int adjust_height = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int adjust_width = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public const int async = 2131361810;
			
			// aapt resource value: 0x7f0a000f
			public const int auto = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int blocking = 2131361811;
			
			// aapt resource value: 0x7f0a001e
			public const int calendar_grid = 2131361822;
			
			// aapt resource value: 0x7f0a0016
			public const int calendar_view = 2131361814;
			
			// aapt resource value: 0x7f0a0023
			public const int cancel_action = 2131361827;
			
			// aapt resource value: 0x7f0a002b
			public const int chronometer = 2131361835;
			
			// aapt resource value: 0x7f0a001a
			public const int currentLocationButton = 2131361818;
			
			// aapt resource value: 0x7f0a0010
			public const int dark = 2131361808;
			
			// aapt resource value: 0x7f0a0032
			public const int end_padder = 2131361842;
			
			// aapt resource value: 0x7f0a0014
			public const int forever = 2131361812;
			
			// aapt resource value: 0x7f0a0005
			public const int hybrid = 2131361797;
			
			// aapt resource value: 0x7f0a002d
			public const int icon = 2131361837;
			
			// aapt resource value: 0x7f0a0031
			public const int icon_group = 2131361841;
			
			// aapt resource value: 0x7f0a000c
			public const int icon_only = 2131361804;
			
			// aapt resource value: 0x7f0a002c
			public const int info = 2131361836;
			
			// aapt resource value: 0x7f0a0015
			public const int italic = 2131361813;
			
			// aapt resource value: 0x7f0a0018
			public const int left_arrow = 2131361816;
			
			// aapt resource value: 0x7f0a0011
			public const int light = 2131361809;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a001d
			public const int map = 2131361821;
			
			// aapt resource value: 0x7f0a0025
			public const int media_actions = 2131361829;
			
			// aapt resource value: 0x7f0a0006
			public const int none = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int normal = 2131361799;
			
			// aapt resource value: 0x7f0a002f
			public const int notification_background = 2131361839;
			
			// aapt resource value: 0x7f0a0028
			public const int notification_main_column = 2131361832;
			
			// aapt resource value: 0x7f0a0027
			public const int notification_main_column_container = 2131361831;
			
			// aapt resource value: 0x7f0a0035
			public const int place_autocomplete_clear_button = 2131361845;
			
			// aapt resource value: 0x7f0a0037
			public const int place_autocomplete_powered_by_google = 2131361847;
			
			// aapt resource value: 0x7f0a0039
			public const int place_autocomplete_prediction_primary_text = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int place_autocomplete_prediction_secondary_text = 2131361850;
			
			// aapt resource value: 0x7f0a0038
			public const int place_autocomplete_progress = 2131361848;
			
			// aapt resource value: 0x7f0a0033
			public const int place_autocomplete_search_button = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int place_autocomplete_search_input = 2131361844;
			
			// aapt resource value: 0x7f0a0036
			public const int place_autocomplete_separator = 2131361846;
			
			// aapt resource value: 0x7f0a0017
			public const int right_arrow = 2131361815;
			
			// aapt resource value: 0x7f0a002e
			public const int right_icon = 2131361838;
			
			// aapt resource value: 0x7f0a0029
			public const int right_side = 2131361833;
			
			// aapt resource value: 0x7f0a0008
			public const int satellite = 2131361800;
			
			// aapt resource value: 0x7f0a000d
			public const int standard = 2131361805;
			
			// aapt resource value: 0x7f0a001b
			public const int startButton = 2131361819;
			
			// aapt resource value: 0x7f0a0024
			public const int status_bar_latest_event_content = 2131361828;
			
			// aapt resource value: 0x7f0a001c
			public const int stopButton = 2131361820;
			
			// aapt resource value: 0x7f0a0009
			public const int terrain = 2131361801;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a002a
			public const int time = 2131361834;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a000e
			public const int wide = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int cancel_button_image_alpha = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int status_bar_notification_info_maxnum = 2131230722;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Map = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int month = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_action = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_action_tombstone = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_media_action = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_media_cancel_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_big_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_big_media_custom = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media_narrow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_narrow_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_custom_big = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_icon_group = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_lines_media = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_media = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_media_custom = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_part_chronometer = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_part_time = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int place_autocomplete_fragment = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int place_autocomplete_item_powered_by_google = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int place_autocomplete_item_prediction = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int place_autocomplete_progress = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int week = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int app_name = 2130968603;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_install_button = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_install_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_install_title = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_notification_ticker = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_unknown_issue = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_unsupported_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_update_button = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_update_text = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_update_title = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_updating_text = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_wear_update_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int common_signin_button_text = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int common_signin_button_text_long = 2130968601;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int place_autocomplete_clear_button = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int place_autocomplete_search_hint = 2130968584;
			
			// aapt resource value: 0x7f04001a
			public const int status_bar_notification_info_overflow = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int title = 2130968604;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int TextAppearance_Compat_Notification = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int TextAppearance_Compat_Notification_Info = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int TextAppearance_Compat_Notification_Line2 = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification_Media = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int TextAppearance_Compat_Notification_Time = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int TextAppearance_Compat_Notification_Title = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int Widget_Compat_NotificationActionContainer = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Widget_Compat_NotificationActionText = 2131165198;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
